### ISSUE TITLE
ERROR Binding cannot be changed after it has been used.

### ISSUE THREAD

**Issue by BEDIRHANSAMSA** [macgile/DataGridFilter#101]
When first data fill it works, after item source data change firing Binding cannot be changed after it has been used error.

```csharp
<filterDataGrid:FilterDataGrid Grid.Row="1" x:Name="DataGrid" Style="{StaticResource MaterialDesignDataGrid}"
                                           AlternatingRowBackground="WhiteSmoke"
                                           AlternationCount="2"
                                           AutoGenerateColumns="False"
                                           Background="Transparent"
                                           CanUserAddRows="False"
                                           DateFormatString="dd-MM-yy hh:mm:ss"
                                           FilterLanguage="Turkish"
                                           HorizontalGridLinesBrush="LightGray"
                                           IsReadOnly="True"
                                           SelectedCellsChanged="DataGrid_OnSelectedCellsChanged"
                                           ItemsSource="{Binding Products, UpdateSourceTrigger=PropertyChanged}"
                                           ShowElapsedTime="True"
                                           EnableColumnVirtualization="True"
                                           EnableRowVirtualization="True"
                                           ShowStatusBar="True"
                                           VerticalGridLinesBrush="LightGray"
                                           VerticalScrollBarVisibility="Visible"
                                           VirtualizingStackPanel.IsVirtualizing="True"
                                           SelectedItem="{Binding SelectedProduct}"
                                           MouseDoubleClick="{markupExtensions:EventBinding ProductsDataGridMouseDoubleClick}">
                    <filterDataGrid:FilterDataGrid.Columns>
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.ID}" Binding="{Binding Id}" IsColumnFiltered="True"/>
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.Status}" Binding="{Binding Status.Name}" IsColumnFiltered="True"/>
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.Name}" Binding="{Binding Name}" IsColumnFiltered="True"/>
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.Kdv}" Width="60" Binding="{Binding Kdv}" IsColumnFiltered="True"/>
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.StockCode}" Binding="{Binding StockCode}" IsColumnFiltered="True"/>
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.Amount}" Binding="{Binding Amount}" IsColumnFiltered="True"/>   
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.DimensionalWeight}" Binding="{Binding DimensionalWeight}" IsColumnFiltered="True"/>
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.InvoiceName}" Binding="{Binding InvoiceName}" IsColumnFiltered="True"/>
                        <filterDataGrid:DataGridTextColumn Header="{x:Static lang:Resources.EInvoiceName}" Binding="{Binding EInvoiceName}" IsColumnFiltered="True"/>
</filterDataGrid:FilterDataGrid>  
```

After click search button
```csharp
        Orders = _orderService.GetAll(predicate, true);
```

https://github.com/macgile/DataGridFilter/blob/869f6c6e20e912ef872490d12504e2c3c8b292fe/FilterDataGrid.Net/FilterDataGrid.cs#L712

```
System.InvalidOperationException: 'Binding cannot be changed after it has been used.'

   at System.Windows.Data.BindingBase.CheckSealed()
   at System.Windows.Data.Binding.set_ConverterCulture(CultureInfo value)
   at FilterDataGrid.FilterDataGrid.GeneratingCustomsColumn() in E:\Projects\Business\AkilliSatici\desktop\Libraries\DataGridFilter\FilterDataGrid.Net\FilterDataGrid.cs:line 712
   at FilterDataGrid.FilterDataGrid.OnItemsSourceChanged(IEnumerable oldValue, IEnumerable newValue) in E:\Projects\Business\AkilliSatici\desktop\Libraries\DataGridFilter\FilterDataGrid.Net\FilterDataGrid.cs:line 496
   at System.Windows.Controls.ItemsControl.OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at MS.Internal.Data.PropertyPathWorker.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Entegration.WPF.ViewModel.Base.BaseViewModel.OnPropertyChanged(String propertyName) in E:\Projects\Business\AkilliSatici\desktop\Entegration\Entegration\ViewModel\Base\BaseViewModel.cs:line 32
   at Entegration.WPF.ViewModel.Product.ProductListViewModel.set_Products(ObservableCollection`1 value) in E:\Projects\Business\AkilliSatici\desktop\Entegration\Entegration\ViewModel\Product\ProductListViewModel.cs:line 50
   at Entegration.WPF.ViewModel.Product.ProductListViewModel.Search() in E:\Projects\Business\AkilliSatici\desktop\Entegration\Entegration\ViewModel\Product\ProductListViewModel.cs:line 224
   at Entegration.WPF.ViewModel.Base.RelayCommand.Execute(Object parameter) in E:\Projects\Business\AkilliSatici\desktop\Entegration\Entegration\ViewModel\Base\RelayCommand.cs:line 45
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ToggleButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by BEDIRHANSAMSA** [comment]
This is a little awkward. When the first load in GeneratingCustomsColumn method columns variable Count 0.
https://github.com/macgile/DataGridFilter/blob/869f6c6e20e912ef872490d12504e2c3c8b292fe/FilterDataGrid.Net/FilterDataGrid.cs#L668-L674

After search button click, now GeneratingCustomsColumn variable count is exist but this time col.HeaderTemplate is always null 
https://github.com/macgile/DataGridFilter/blob/869f6c6e20e912ef872490d12504e2c3c8b292fe/FilterDataGrid.Net/FilterDataGrid.cs#L681

**Comment by BEDIRHANSAMSA** [comment]
I solved this problem. Main problem is my BaseViewModel, this is not related to the library.

**Comment by Angyro** [comment]
how did you fix it in your code? I can't update my ItemSource

**Comment by BEDIRHANSAMSA** [comment]
> how did you fix it in your code? I can't update my ItemSource

In my case, the error was loading the viewmodel before the UI was loaded, this was causing the error
