### ISSUE TITLE
DataGridTextColumn.HeaderStyle & position button filter

### ISSUE THREAD

**Issue by mutik-ar** [macgile/DataGridFilter#68]
Hi,
version 1.2.5
When I style the column headers, even empty,
            <control:FilterDataGrid.ColumnHeaderStyle>
                <Style/>
            </control:FilterDataGrid.ColumnHeaderStyle>

the position of the filter button moves from the right edge of the column, in ColumnWidth=SizeToHeader mode, to the right edge of the text, and if ColumnWidth=*, then to the left edge of the column. If part of the column with text is outside the window border on the right, then when you click the filter button, an error occurs:
System.ArgumentException
  HResult=0x80070057
  Message="-90.01333333333332" is not a valid value for the "MaxWidth" property.
  Source=WindowsBase
  stacktrace:
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.FrameworkElement.set_MaxWidth(Double value)
   at FilterDataGrid.FilterDataGrid.PopupPlacement(FrameworkElement grid, FrameworkElement header) in D:\_Docs\Md\FilterDataGrid.1.2.5.0\FilterDataGrid.Net5.0\FilterDataGrid.cs:line 1266
   at FilterDataGrid.FilterDataGrid.<ShowFilterCommand>d__119.MoveNext() in D:\_Docs\Md\FilterDataGrid.1.2.5.0\FilterDataGrid.Net5.0\FilterDataGrid.cs:line 1071

  This exception was originally thrown at this call stack:
    [external code]
    FilterDataGrid.FilterDataGrid.PopupPlacement(System.Windows.FrameworkElement, System.Windows.FrameworkElement) in FilterDataGrid.cs
    FilterDataGrid.FilterDataGrid.ShowFilterCommand(object, System.Windows.Input.ExecutedRoutedEventArgs) in FilterDataGrid.cs

**Comment by macgile** [comment]
It doesn't work because you are overriding the header template I defined by your own style.
Look at the XAML code of the headers (DataGridHeaderTemplate) and you will understand that the width of the headers is calculated by retrieving the ActualWidth of the parent ContentPresenter of the grid that contains the filter button.

best regards

**Comment by mutik-ar** [comment]
Thanks for your answer,
What helped me was that I added to my style from FilterDataGrid.xaml row 267:
        <Setter Property="HorizontalContentAlignment" Value="Stretch" />

**Comment by mutik-ar** [comment]
Setter Property="HorizontalContentAlignment" Value="Stretch"

**Comment by mutik-ar** [comment]
Yes, 
I thought if I repeat the default style, then the filter button will return to its place on the right side of the column border. And so it happened. In addition, I added other settings to my style. Everything is working. thanks for FilterDataGrid.
